version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile   # ⬅️ Use your custom Dockerfile
    container_name: php-food-app
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php83-mysql
    restart: always
    environment:
      MYSQL_DATABASE: food_app_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php83-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db_data:
