version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile   # ⬅️ Use your custom Dockerfile
    container_name: php-food-app
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - MESSENGER_TRANSPORT_DSN=redis://redis:6379/messages
      - DATABASE_URL=mysql://user:secret@db:3306/food_app_db

  db:
    image: mysql:8.0
    container_name: php83-mysql
    restart: always
    environment:
      MYSQL_DATABASE: food_app_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php83-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"      # For backend communication
      - "15672:15672"    # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-work-consumer
    depends_on:
      - app
      - rabbitmq
      - db
    command: php /var/www/public/reportConsumer.php
    volumes:
      - .:/var/www
    environment:
      - DATABASE_URL=mysql://user:secret@db:3306/food_app_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest

volumes:
  db_data:
