version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    hostname: app1
    volumes:
      - .:/app
      - ./config:/config
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - MESSENGER_TRANSPORT_DSN=redis://redis:6379/messages
      - DATABASE_URL=mysql://root:root@db:3306/food_app_db
      - SERVER_NAME=:80
    networks:
      - backend
    command: ./docker-entrypoint.sh
    
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    hostname: app2
    volumes:
      - .:/app
      - ./config:/config
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - MESSENGER_TRANSPORT_DSN=redis://redis:6379/messages
      - DATABASE_URL=mysql://root:root@db:3306/food_app_db
      - SERVER_NAME=:80
    networks:
      - backend
    command: ./docker-entrypoint.sh

  loadbalancer:
    image: caddy:2-alpine
    container_name: loadbalancer
    ports:
      - "8080:80"
      - "2019:2019"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - ./config:/config
    depends_on:
      - app1
      - app2
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: php83-mysql
    restart: always
    environment:
      MYSQL_DATABASE: food_app_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php83-phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - backend
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-work-consumer
    depends_on:
      - app1
      - app2
      - rabbitmq
      - db
    command: sh -c "php /app/src/views/reports/reportConsumer.php & \
                php /app/src/seeders/seederConsumer.php"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/food_app_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - backend

volumes:
  db_data:
  redis_data:
  caddy_data:

networks:
  backend:
    driver: bridge
